#include "ColorPickerStrings.hpp"
#include "I18N.hpp"

#include <nlohmann/json.hpp>

namespace Slic3r::GUI {

// English palette names are stable translation keys; RAL codes stay in the page data.
nlohmann::json color_picker_ui_strings()
{
    return {
        {"Color Picker", _u8L("Color Picker")},
        {"Basic Colors", _u8L("Basic Colors")},
        {"Orca Palette", _u8L("Orca Palette")},
        {"RAL Classic", _u8L("RAL Classic")},
        {"Gradients", _u8L("Gradients")},
        {"Color", _u8L("Color")},
        {"Gradient", _u8L("Gradient")},
        {"Hex color", _u8L("Hex color")},
        {"Opacity", _u8L("Opacity")},
        {"Opacity percent", _u8L("Opacity percent")},
        {"Save color", _u8L("Save color")},
        {"Cancel", _u8L("Cancel")},
        {"OK", _u8L("OK")},
        {"Enter a complete hexadecimal color", _u8L("Enter a complete hexadecimal color")},
        {"The current multi-color selection is kept until you choose a different color.", _u8L("The current multi-color selection is kept until you choose a different color.")},
        {"Red", _u8L("Red")},
        {"Crimson", _u8L("Crimson")},
        {"Orange red", _u8L("Orange red")},
        {"Tomato", _u8L("Tomato")},
        {"Orange", _u8L("Orange")},
        {"Dark orange", _u8L("Dark orange")},
        {"Gold", _u8L("Gold")},
        {"Burly wood", _u8L("Burly wood")},
        {"Bisque", _u8L("Bisque")},
        {"Misty rose", _u8L("Misty rose")},
        {"Yellow", _u8L("Yellow")},
        {"Light yellow", _u8L("Light yellow")},
        {"Lemon chiffon", _u8L("Lemon chiffon")},
        {"Beige", _u8L("Beige")},
        {"Light golden rod yellow", _u8L("Light golden rod yellow")},
        {"Pale golden rod", _u8L("Pale golden rod")},
        {"Khaki", _u8L("Khaki")},
        {"Dark khaki", _u8L("Dark khaki")},
        {"Peach puff", _u8L("Peach puff")},
        {"Moccasin", _u8L("Moccasin")},
        {"Papaya whip", _u8L("Papaya whip")},
        {"Blanched almond", _u8L("Blanched almond")},
        {"Antique white", _u8L("Antique white")},
        {"Navajo white", _u8L("Navajo white")},
        {"Wheat", _u8L("Wheat")},
        {"Golden rod", _u8L("Golden rod")},
        {"Chocolate", _u8L("Chocolate")},
        {"Peru", _u8L("Peru")},
        {"Fire brick", _u8L("Fire brick")},
        {"Sienna", _u8L("Sienna")},
        {"Saddle brown", _u8L("Saddle brown")},
        {"Brown", _u8L("Brown")},
        {"Rosy brown", _u8L("Rosy brown")},
        {"Salmon", _u8L("Salmon")},
        {"Light salmon", _u8L("Light salmon")},
        {"Dark salmon", _u8L("Dark salmon")},
        {"Sandy brown", _u8L("Sandy brown")},
        {"Coral", _u8L("Coral")},
        {"Light coral", _u8L("Light coral")},
        {"Indian red", _u8L("Indian red")},
        {"Dark red", _u8L("Dark red")},
        {"Maroon", _u8L("Maroon")},
        {"Green yellow", _u8L("Green yellow")},
        {"Yellow green", _u8L("Yellow green")},
        {"Chartreuse", _u8L("Chartreuse")},
        {"Lawn green", _u8L("Lawn green")},
        {"Lime green", _u8L("Lime green")},
        {"Spring green", _u8L("Spring green")},
        {"Medium spring green", _u8L("Medium spring green")},
        {"Lime", _u8L("Lime")},
        {"Green", _u8L("Green")},
        {"Forest green", _u8L("Forest green")},
        {"Dark green", _u8L("Dark green")},
        {"Olive drab", _u8L("Olive drab")},
        {"Olive", _u8L("Olive")},
        {"Dark olive green", _u8L("Dark olive green")},
        {"Pale green", _u8L("Pale green")},
        {"Light green", _u8L("Light green")},
        {"Medium sea green", _u8L("Medium sea green")},
        {"Sea green", _u8L("Sea green")},
        {"Dark sea green", _u8L("Dark sea green")},
        {"Cadet blue", _u8L("Cadet blue")},
        {"Medium aqua marine", _u8L("Medium aqua marine")},
        {"Turquoise", _u8L("Turquoise")},
        {"Medium turquoise", _u8L("Medium turquoise")},
        {"Dark turquoise", _u8L("Dark turquoise")},
        {"Pale turquoise", _u8L("Pale turquoise")},
        {"Aqua", _u8L("Aqua")},
        {"Cyan", _u8L("Cyan")},
        {"Light cyan", _u8L("Light cyan")},
        {"Mint cream", _u8L("Mint cream")},
        {"Honey dew", _u8L("Honey dew")},
        {"Aquamarine", _u8L("Aquamarine")},
        {"Light sea green", _u8L("Light sea green")},
        {"Dark cyan", _u8L("Dark cyan")},
        {"Teal", _u8L("Teal")},
        {"Dark slate gray", _u8L("Dark slate gray")},
        {"Light slate gray", _u8L("Light slate gray")},
        {"Slate gray", _u8L("Slate gray")},
        {"Deep sky blue", _u8L("Deep sky blue")},
        {"Dodger Blue", _u8L("Dodger Blue")},
        {"Sky blue", _u8L("Sky blue")},
        {"Light sky blue", _u8L("Light sky blue")},
        {"Light blue", _u8L("Light blue")},
        {"Powder blue", _u8L("Powder blue")},
        {"Light steel blue", _u8L("Light steel blue")},
        {"Steel blue", _u8L("Steel blue")},
        {"Cornflower blue", _u8L("Cornflower blue")},
        {"Royal blue", _u8L("Royal blue")},
        {"Blue", _u8L("Blue")},
        {"Medium blue", _u8L("Medium blue")},
        {"Midnight blue", _u8L("Midnight blue")},
        {"Dark blue", _u8L("Dark blue")},
        {"Navy", _u8L("Navy")},
        {"Slate blue", _u8L("Slate blue")},
        {"Dark slate blue", _u8L("Dark slate blue")},
        {"Medium slate blue", _u8L("Medium slate blue")},
        {"Blue violet", _u8L("Blue violet")},
        {"Indigo", _u8L("Indigo")},
        {"Dark violet", _u8L("Dark violet")},
        {"Dark orchid", _u8L("Dark orchid")},
        {"Medium orchid", _u8L("Medium orchid")},
        {"Orchid", _u8L("Orchid")},
        {"Violet", _u8L("Violet")},
        {"Medium purple", _u8L("Medium purple")},
        {"Purple", _u8L("Purple")},
        {"Rebecca purple", _u8L("Rebecca purple")},
        {"Medium violet red", _u8L("Medium violet red")},
        {"PaleV violet red", _u8L("PaleV violet red")},
        {"Deep pink", _u8L("Deep pink")},
        {"Hot pink", _u8L("Hot pink")},
        {"Light pink", _u8L("Light pink")},
        {"Pink", _u8L("Pink")},
        {"Plum", _u8L("Plum")},
        {"Thistle", _u8L("Thistle")},
        {"Magenta", _u8L("Magenta")},
        {"Fuchsia", _u8L("Fuchsia")},
        {"Dark magenta", _u8L("Dark magenta")},
        {"Linen", _u8L("Linen")},
        {"Old lace", _u8L("Old lace")},
        {"Sea shell", _u8L("Sea shell")},
        {"Ivory", _u8L("Ivory")},
        {"Floral white", _u8L("Floral white")},
        {"Lavender blush", _u8L("Lavender blush")},
        {"Ghost white", _u8L("Ghost white")},
        {"Alice blue", _u8L("Alice blue")},
        {"Lavender", _u8L("Lavender")},
        {"White smoke", _u8L("White smoke")},
        {"Gainsboro", _u8L("Gainsboro")},
        {"Black", _u8L("Black")},
        {"White", _u8L("White")},
        {"Coral fire", _u8L("Coral fire")},
        {"Sea anemone", _u8L("Sea anemone")},
        {"Deep abyss", _u8L("Deep abyss")},
        {"Lobster red", _u8L("Lobster red")},
        {"Sandy clay", _u8L("Sandy clay")},
        {"Driftwood", _u8L("Driftwood")},
        {"Sea buckthorn", _u8L("Sea buckthorn")},
        {"Sunset reef", _u8L("Sunset reef")},
        {"Tiger coral", _u8L("Tiger coral")},
        {"Pink coral", _u8L("Pink coral")},
        {"Seashell glow", _u8L("Seashell glow")},
        {"Sand", _u8L("Sand")},
        {"Golden kelp", _u8L("Golden kelp")},
        {"Sunlit dune", _u8L("Sunlit dune")},
        {"Amber nautilus", _u8L("Amber nautilus")},
        {"Sea lemon", _u8L("Sea lemon")},
        {"Pale starfish", _u8L("Pale starfish")},
        {"Spring tide", _u8L("Spring tide")},
        {"Lime algae", _u8L("Lime algae")},
        {"Sea grass", _u8L("Sea grass")},
        {"Neon plankton", _u8L("Neon plankton")},
        {"Kelp forest", _u8L("Kelp forest")},
        {"Emerald wave", _u8L("Emerald wave")},
        {"Whale shadow", _u8L("Whale shadow")},
        {"Sea turtle", _u8L("Sea turtle")},
        {"Lagoon", _u8L("Lagoon")},
        {"Tropical current", _u8L("Tropical current")},
        {"Midnight trench", _u8L("Midnight trench")},
        {"Dark kelp", _u8L("Dark kelp")},
        {"Crystal surf", _u8L("Crystal surf")},
        {"Turquoise bay", _u8L("Turquoise bay")},
        {"Sky over reef", _u8L("Sky over reef")},
        {"Shallow sky", _u8L("Shallow sky")},
        {"Electric bel", _u8L("Electric bel")},
        {"Dolphin", _u8L("Dolphin")},
        {"Ocean depths", _u8L("Ocean depths")},
        {"Whale", _u8L("Whale")},
        {"Indigo abyss", _u8L("Indigo abyss")},
        {"Sea urchin", _u8L("Sea urchin")},
        {"Lavender coral", _u8L("Lavender coral")},
        {"Violet tide", _u8L("Violet tide")},
        {"Deep sea orchid", _u8L("Deep sea orchid")},
        {"Neon jelly", _u8L("Neon jelly")},
        {"Fuchsia coral", _u8L("Fuchsia coral")},
        {"Pink jellyfish", _u8L("Pink jellyfish")},
        {"Foam", _u8L("Foam")},
        {"Seashell white", _u8L("Seashell white")},
        {"Pebble gray", _u8L("Pebble gray")},
        {"Storm cloud", _u8L("Storm cloud")},
        {"Ink black", _u8L("Ink black")},
        {"Green beige", _u8L("Green beige")},
        {"Sand yellow", _u8L("Sand yellow")},
        {"Signal yellow", _u8L("Signal yellow")},
        {"Golden yellow", _u8L("Golden yellow")},
        {"Honey yellow", _u8L("Honey yellow")},
        {"Maize yellow", _u8L("Maize yellow")},
        {"Dalmatian yellow", _u8L("Dalmatian yellow")},
        {"Brown beige", _u8L("Brown beige")},
        {"Lemon yellow", _u8L("Lemon yellow")},
        {"Oyster white", _u8L("Oyster white")},
        {"Light ivory", _u8L("Light ivory")},
        {"Zinc yellow", _u8L("Zinc yellow")},
        {"Grey beige", _u8L("Grey beige")},
        {"Olive yellow", _u8L("Olive yellow")},
        {"Rape yellow", _u8L("Rape yellow")},
        {"Traffic yellow", _u8L("Traffic yellow")},
        {"Ochre yellow", _u8L("Ochre yellow")},
        {"Traffic orange yellow", _u8L("Traffic orange yellow")},
        {"Curry", _u8L("Curry")},
        {"Melon yellow", _u8L("Melon yellow")},
        {"Broom yellow", _u8L("Broom yellow")},
        {"Dahlia yellow", _u8L("Dahlia yellow")},
        {"Pastel yellow", _u8L("Pastel yellow")},
        {"Pearl beige", _u8L("Pearl beige")},
        {"Pearl gold", _u8L("Pearl gold")},
        {"Sun yellow", _u8L("Sun yellow")},
        {"Yellow orange", _u8L("Yellow orange")},
        {"Deep orange", _u8L("Deep orange")},
        {"Vermilion", _u8L("Vermilion")},
        {"Pearl orange", _u8L("Pearl orange")},
        {"Pure orange", _u8L("Pure orange")},
        {"Luminous orange", _u8L("Luminous orange")},
        {"Luminous bright orange", _u8L("Luminous bright orange")},
        {"Bright red orange", _u8L("Bright red orange")},
        {"Traffic orange", _u8L("Traffic orange")},
        {"Signal orange", _u8L("Signal orange")},
        {"Salmon orange", _u8L("Salmon orange")},
        {"Pearl pink", _u8L("Pearl pink")},
        {"Copper orange", _u8L("Copper orange")},
        {"Signal brown", _u8L("Signal brown")},
        {"Fir orange", _u8L("Fir orange")},
        {"Signal red", _u8L("Signal red")},
        {"Luminous red", _u8L("Luminous red")},
        {"Carmine red", _u8L("Carmine red")},
        {"Pearl carmine red", _u8L("Pearl carmine red")},
        {"Pure red", _u8L("Pure red")},
        {"Luminous deep red", _u8L("Luminous deep red")},
        {"Currant red", _u8L("Currant red")},
        {"Pearl ruby red", _u8L("Pearl ruby red")},
        {"Fire red", _u8L("Fire red")},
        {"Ruby red", _u8L("Ruby red")},
        {"Purple red", _u8L("Purple red")},
        {"Wine red", _u8L("Wine red")},
        {"Black red", _u8L("Black red")},
        {"Oxide red", _u8L("Oxide red")},
        {"Brown red", _u8L("Brown red")},
        {"Pine red", _u8L("Pine red")},
        {"Tomato red", _u8L("Tomato red")},
        {"Antique pink", _u8L("Antique pink")},
        {"Coral red", _u8L("Coral red")},
        {"Rose", _u8L("Rose")},
        {"Strawberry red", _u8L("Strawberry red")},
        {"Traffic red", _u8L("Traffic red")},
        {"Salmon pink", _u8L("Salmon pink")},
        {"Luminous rose", _u8L("Luminous rose")},
        {"Luminous bright red", _u8L("Luminous bright red")},
        {"Raspberry red", _u8L("Raspberry red")},
        {"Orient red", _u8L("Orient red")},
        {"Pearl ruby", _u8L("Pearl ruby")},
        {"Red purple", _u8L("Red purple")},
        {"Red violet", _u8L("Red violet")},
        {"Heather violet", _u8L("Heather violet")},
        {"Bordeaux violet", _u8L("Bordeaux violet")},
        {"Mahogany", _u8L("Mahogany")},
        {"Grey purple", _u8L("Grey purple")},
        {"Signal violet", _u8L("Signal violet")},
        {"Fir green", _u8L("Fir green")},
        {"Sabine grey", _u8L("Sabine grey")},
        {"Pearl violet", _u8L("Pearl violet")},
        {"Pearl blackberry", _u8L("Pearl blackberry")},
        {"Green blue", _u8L("Green blue")},
        {"Ultramarine blue", _u8L("Ultramarine blue")},
        {"Sapphire blue", _u8L("Sapphire blue")},
        {"Black blue", _u8L("Black blue")},
        {"Signal blue", _u8L("Signal blue")},
        {"Brilliant blue", _u8L("Brilliant blue")},
        {"Grey blue", _u8L("Grey blue")},
        {"Azure blue", _u8L("Azure blue")},
        {"Gentian blue", _u8L("Gentian blue")},
        {"Cobalt blue", _u8L("Cobalt blue")},
        {"Pigeon blue", _u8L("Pigeon blue")},
        {"Traffic blue", _u8L("Traffic blue")},
        {"Turquoise blue", _u8L("Turquoise blue")},
        {"Capsanthin violet", _u8L("Capsanthin violet")},
        {"Ocean blue", _u8L("Ocean blue")},
        {"Water blue", _u8L("Water blue")},
        {"Night blue", _u8L("Night blue")},
        {"Distant blue", _u8L("Distant blue")},
        {"Pastel blue", _u8L("Pastel blue")},
        {"Pearl gentian blue", _u8L("Pearl gentian blue")},
        {"Pearl midnight blue", _u8L("Pearl midnight blue")},
        {"Patina green", _u8L("Patina green")},
        {"Emerald green", _u8L("Emerald green")},
        {"Leaf green", _u8L("Leaf green")},
        {"Olive green", _u8L("Olive green")},
        {"Blue green", _u8L("Blue green")},
        {"Moss green", _u8L("Moss green")},
        {"Grey olive", _u8L("Grey olive")},
        {"Pine green", _u8L("Pine green")},
        {"Pine brown", _u8L("Pine brown")},
        {"Grass green", _u8L("Grass green")},
        {"Reseda green", _u8L("Reseda green")},
        {"Brown green", _u8L("Brown green")},
        {"Reed green", _u8L("Reed green")},
        {"Black green", _u8L("Black green")},
        {"Turquoise green", _u8L("Turquoise green")},
        {"May green", _u8L("May green")},
        {"Chrome oxide green", _u8L("Chrome oxide green")},
        {"Traffic green", _u8L("Traffic green")},
        {"Fern green", _u8L("Fern green")},
        {"Opal green", _u8L("Opal green")},
        {"Mint green", _u8L("Mint green")},
        {"Bronze green", _u8L("Bronze green")},
        {"Pearl green", _u8L("Pearl green")},
        {"Sax turquoise", _u8L("Sax turquoise")},
        {"Pearl turquoise", _u8L("Pearl turquoise")},
        {"Pearl jade", _u8L("Pearl jade")},
        {"Pure green", _u8L("Pure green")},
        {"Luminous green", _u8L("Luminous green")},
        {"Squirrel grey", _u8L("Squirrel grey")},
        {"Silver grey", _u8L("Silver grey")},
        {"Olivestone", _u8L("Olivestone")},
        {"Moss grey", _u8L("Moss grey")},
        {"Signal grey", _u8L("Signal grey")},
        {"Mouse grey", _u8L("Mouse grey")},
        {"Beige grey", _u8L("Beige grey")},
        {"Khaki grey", _u8L("Khaki grey")},
        {"Green grey", _u8L("Green grey")},
        {"Tarpaulin grey", _u8L("Tarpaulin grey")},
        {"Iron grey", _u8L("Iron grey")},
        {"Basalt grey", _u8L("Basalt grey")},
        {"Brown grey", _u8L("Brown grey")},
        {"Slate grey", _u8L("Slate grey")},
        {"Anthracite grey", _u8L("Anthracite grey")},
        {"Light grey", _u8L("Light grey")},
        {"Umber grey", _u8L("Umber grey")},
        {"Concrete grey", _u8L("Concrete grey")},
        {"Graphite grey", _u8L("Graphite grey")},
        {"Granite grey", _u8L("Granite grey")},
        {"Stone grey", _u8L("Stone grey")},
        {"Pebble grey", _u8L("Pebble grey")},
        {"Cement grey", _u8L("Cement grey")},
        {"Yellow grey", _u8L("Yellow grey")},
        {"Platinum grey", _u8L("Platinum grey")},
        {"Dusty grey", _u8L("Dusty grey")},
        {"Agate grey", _u8L("Agate grey")},
        {"Quartz grey", _u8L("Quartz grey")},
        {"Window grey", _u8L("Window grey")},
        {"Traffic grey A", _u8L("Traffic grey A")},
        {"Traffic grey B", _u8L("Traffic grey B")},
        {"Silk grey", _u8L("Silk grey")},
        {"Telegrey 1", _u8L("Telegrey 1")},
        {"Telegrey 2", _u8L("Telegrey 2")},
        {"Telegrey 4", _u8L("Telegrey 4")},
        {"Pearl mouse grey", _u8L("Pearl mouse grey")},
        {"Green brown", _u8L("Green brown")},
        {"Ochre brown", _u8L("Ochre brown")},
        {"Clay brown", _u8L("Clay brown")},
        {"Copper brown", _u8L("Copper brown")},
        {"Chocolate brown", _u8L("Chocolate brown")},
        {"Olive brown", _u8L("Olive brown")},
        {"Nut brown", _u8L("Nut brown")},
        {"Red brown", _u8L("Red brown")},
        {"Sepia brown", _u8L("Sepia brown")},
        {"Chestnut brown", _u8L("Chestnut brown")},
        {"Mahogany brown", _u8L("Mahogany brown")},
        {"Grey brown", _u8L("Grey brown")},
        {"Pearl copper", _u8L("Pearl copper")},
        {"Beige brown", _u8L("Beige brown")},
        {"Pearl mocha brown", _u8L("Pearl mocha brown")},
        {"Earth brown", _u8L("Earth brown")},
        {"Pearl brown", _u8L("Pearl brown")},
        {"Cream", _u8L("Cream")},
        {"Grey white", _u8L("Grey white")},
        {"Signal white", _u8L("Signal white")},
        {"Signal black", _u8L("Signal black")},
        {"Jet black", _u8L("Jet black")},
        {"White aluminium", _u8L("White aluminium")},
        {"Grey aluminium", _u8L("Grey aluminium")},
        {"Pure white", _u8L("Pure white")},
        {"Graphite black", _u8L("Graphite black")},
        {"Traffic white", _u8L("Traffic white")},
        {"Traffic black", _u8L("Traffic black")},
        {"Papyrus white", _u8L("Papyrus white")},
        {"Pearl light grey", _u8L("Pearl light grey")},
        {"Pearl", _u8L("Pearl")},
        {"Silver", _u8L("Silver")},
        {"Copper", _u8L("Copper")},
        {"Brass", _u8L("Brass")}
    };
}

} // namespace Slic3r::GUI
